info:
  contact:
    email: prosper.abouar@gmail.com
    name: Prosper Abouar
  description: This is the API documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API Documentation
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer:
    description: Enter Bearer with space and your token
    in: header
    name: Bearer
    type: apiKey
  X-API-Key:
    description: Enter the API key to have access
    in: header
    name: ApiKey
    type: apiKey
swagger: "2.0"
